<?php

/**
 * @var Chernenko\Tables\Block\Listing $block
 * @var Magento\Framework\Escaper $escaper
 */

?>
<p><strong>Repo:</strong></p>
<p>
    <a href="https://github.com/serhii-chernenko/magento2-ui-tables" target="_blank">
        <strong>https://github.com/serhii-chernenko/magento2-ui-tables</strong>
    </a>
</p>
<p><strong>Ideas &amp; Advantages:</strong></p>
<ul>
    <li>The tables component allows to display data from a data source in a tabular form.</li>
    <li>You can add new or disable existing additional components such as search, amount, and pagination.</li>
    <li>You can extend any components to rewrite methods to add custom logic based on the already existing.</li>
    <li>You can flexibly specify what kind of columns have to be displayed.</li>
    <li>Check the mobile view to find additional features like columns title, merging, and others.</li>
</ul>
<p><strong>Todo:</strong></p>
<ul>
    <li>Remove link</li>
    <li>View link</li>
    <li>Details page for a specified item (Controller, Block class, XML examples, UI components, Knockout templates)</li>
</ul>
<p><strong>Dummyjson service:</strong></p>
<p>
    <a href="https://dummyjson.com/docs/" target="_blank">
        <strong>https://dummyjson.com/</strong>
    </a>
</p>
