<?php

/**
 * @var Chernenko\Tables\Block\Listing $block
 * @var Magento\Framework\Escaper $escaper
 */

$scope = $block->getData('scope');
?>
<p><strong>Repo:</strong></p>
<p>
    <a href="https://github.com/serhii-chernenko/magento2-ui-tables" target="_blank">
        <strong>https://github.com/serhii-chernenko/magento2-ui-tables</strong>
    </a>
</p>
<p><strong>Todo:</strong></p>
<ul>
    <li>Remove link</li>
    <li>View link</li>
    <li>Details page for a specified item (Controller, Block class, XML examples, UI components, Knockout templates)</li>
</ul>
<hr/>
<div data-mage-init='{"Magento_Ui/js/core/app": <?= $block->getJsLayout(); ?>}'
     data-bind="scope: '<?= $scope; ?>'"
>
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
