- name: Deploy the Chernenko_Tables module on VPS
  hosts: all
  remote_user: root
  become: yes
  become_user: admin
  environment:
    PATH: "/home/admin/tools/madock:{{ ansible_env.PATH }}"
  vars:
    dir: "{{ VPS_APP_PATH }}"
    log_file: "{{ dir }}/var/log/build.log"
    m2: "madock magento"
    build_commands:
      - maintenance:enable
      - setup:upgrade
      - setup:di:compile
      - setup:static-content:deploy
      - cache:flush
      - maintenance:disable
  roles:
    - git_pull
    - magento_build
