- name: Deploy the Chernenko_Tables module on VPS
  hosts: all
  remote_user: inevix
  environment:
    PATH: "/home/inevix/tools/madock:{{ ansible_env.PATH }}"
  vars:
    dir: "/home/inevix/apps/magento-ui-tables"
    log_file: "{{ dir }}/var/log/build.txt"
    m2: "madock magento"
    build_commands:
      - maintenance:enable
      - setup:upgrade
      - setup:di:compile
      - setup:static-content:deploy
      - cache:flush
      - maintenance:disable
  roles:
    - git_pull
    - magento_build
