- name: Update the repo of Chernenko_Tables module on VPS
  git:
    repo: "git@github.com:{{ GITHUB_REPO }}.git"
    dest: "{{ VPS_APP_PATH }}/app/code/Chernenko/Tables"
    update: yes
    single_branch: yes
    version: main
